### ISSUE TITLE
issue running script 

### ISSUE THREAD

**Issue by hedi777** [r8w9a5k/dribbbleBOT#1]
VM159:16 Uncaught TypeError: Cannot read property 'innerHTML' of null
    at run (<anonymous>:16:12)

here is issue i get after running script inside javascript console on chrome, i did login dribbble and am on page full of shots, does it still work on your side ? thanks in advance

**Comment by PlayTimeAlex** [comment]
Created pull request. Maybe developer merge this fix
https://github.com/r8w9a5k/dribbbleBOT/pull/2

**Comment by hedi777** [comment]
thank you very much :-))))

**Comment by r8w9a5k** [comment]
@hedi777  Hi, dribbble changed their layout so script has to be changed also to adapt in  enviroment. Anyway great @PlayTimeAlex did it with a smart approach.
