### ISSUE TITLE
It doesn't Likes shots

### ISSUE THREAD

**Issue by VivaliY** [r8w9a5k/dribbbleBOT#3]
Ive run a script, but all what the script is doing is - swapping to the next shot with out liking it -_-

**Comment by NHammondDesign** [comment]
Same is happening to me. As well, is there a way to randomize the intervals so the system doesn't see our account as just blazing through a bunch of likes one after the other?

**Comment by VivaliY** [comment]
I've made a mine one, based on this code.

Feel free to try this one, and you can randomize time here - > function getDelayTime() {
	return Math.ceil(Math.random()*1000) + 1500; 
( *1000 is a random time in ms, witch you can adjust )

Full script below ( just copy and paste in console )

 

function getDelayTime() {
	return Math.ceil(Math.random()*1000) + 1500;
}

function run(){ 
	var like = document.querySelector(".shot-overlay .like-shot"); //select like button
	var next = document.querySelector(".shot-nav-next a"); //select next page

	function simulateClick (elem) { 		     //core of simulate click function
		var evt = new MouseEvent('click', {
			bubbles: true,
			cancelable: true,
			view: window 
		});
		var canceled = !elem.dispatchEvent(evt); // end of core simulate click function
	};

	simulateClick(like);	//then like
	simulateClick(next);

	setTimeout(run, getDelayTime())
}

setTimeout(run, getDelayTime()); 

void 0;

**Comment by r8w9a5k** [comment]
Hey, I updated dribbbleBOT.js, please try it now and let me know :)
